spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticateFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservation/**
          filters:
            - AuthenticateFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/ws/**

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/room/**
          filters:
            - AuthenticateFilter

      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/